#! /usr/bin/env bash
# Making an assumption that jq and zeek-config on $PATH

if ! command -v jq &> /dev/null; then
    echo "jq is not on PATH."
    exit 1
fi

if ! command -v zeek-config &> /dev/null; then
    echo "zeek-config is not on PATH"
    exit 1
fi

if [ ! -f "$PACKAGE_JSON" ]; then
  echo "Error: package.json not found"
  exit 1
fi

if [ ! -f "$PACKAGE_LOCK_JSON" ]; then
  echo "Error: package-lock.json not found"
  exit 1
fi

ZEEK_BASE=$(zeek-config --prefix)
NODE_MODULES="/var/lib/zkg/testing/zeekjs-redis/clones/zeekjs-redis/node_modules/"
NODE_MODULES_DIR="${ZEEK_BASE}/$NODE_MODULES"

if [ ! -d "$NODE_MODULES_DIR" ]; then
    echo "Node modules directory does not exist: $NODE_MODULES_DIR"
    exit 1
fi

deps=$(jq -r '.dependencies | keys | .[]' "$PACKAGE_JSON")

missing_count=0
for dep in $deps; do
  if [ ! -d "${NODE_MODULES_DIR}/$dep" ]; then
    echo "Missing: $dep"
    ((missing_count++))
  fi
done

if [ $missing_count -eq 0 ]; then
  echo "All npm packages have been installed."
else
  echo "$missing_count npm packages are missing."
fi
